# Generated by Django 2.1.1 on 2018-10-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_where_to_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='where_to_status',
            field=models.CharField(choices=[('post_list', 'Post List'), ('post_list2', 'Post List2')], default='post_list', max_length=15),
        ),
    ]
